[package]
name = "gomlang-parser-rust-oracle"
version = "0.1.0"
edition = "2024"

[dependencies]
ast = { path = "../../../goml/crates/ast" }
common_defs = { path = "../../../goml/crates/common-defs" }
cst = { path = "../../../goml/crates/cst" }
compiler = { path = "../../../goml/crates/compiler" }
lexer = { path = "../../../goml/crates/lexer" }
parser = { path = "../../../goml/crates/parser" }
text-size = "1.1.1"
