[package]
name = "parser"
version = "0.0.0"
edition.workspace = true

[dependencies]
diagnostics.workspace = true
lexer.workspace = true
rowan.workspace = true
text-size.workspace = true
line-index.workspace = true
pretty.workspace = true

[dev-dependencies]
expect-test.workspace = true
