[package]
name = "wasm-app"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
compiler.workspace = true
im.workspace = true
wasm-bindgen = { version = "0.2.100" }
