[package]
name = "wasm-app"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
parser.workspace = true
cst.workspace = true
ast.workspace = true
compiler.workspace = true
im.workspace = true
wasm-bindgen = { version = "0.2.100" }
diagnostics.workspace = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-bulk-memory"]
